name: Generate Snake

on:
  schedule: # Run at 00:00 UTC every day
    - cron: "0 0 * * *"
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Generate Snake
        uses: Platane/snk@master
        with:
          github_user_name: ${{ saumya1109 }}
          outputs: dist/snake.svg
      - name: Push Snake
        uses: EndBug/add-and-commit@v7
        with:
          add: dist/snake.svg
          message: "Generated snake"
